### ISSUE TITLE
isn't working  

### ISSUE THREAD

**Issue by DaveTesting** [ronreiter/injection-proxy#1]
```

  File "proxy.py", line 67
    except Exception, e:
                    ^
SyntaxError: invalid syntax

```
and if I remove the "try&exception " - 
I get this - 
`
  File "proxy.py", line 64
    url_response = opener.open(outgoing
    ^
IndentationError: unexpected indent
`

I have only download python from python.org and your proxy.py 
do I need something else?

Thanks , 
,

**Comment by ronreiter** [comment]
Seems like you're using Python 3 - this is written to support Python 2. You can make some easy adjustments to have it support Python 3 and send me a pull request. I can do it for you if you wish.

**Comment by DaveTesting** [comment]
OK - 
I have download Python 2 - and it's working now on port 8005 , 
so now I have a proxy server that I can control and inject content to any webpage - right? 
can it handle https pages also  ? or just simple html pages? 

Thanks , 
and very quick response - Thanks !
